# Generated by Django 6.0 on 2025-12-29 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Department name (e.g., English Department, Science Department)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Brief description of this department",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date when this department was added",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date when this department was last updated",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this department is currently active",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "db_table": "department",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="department_name_9f4150_idx"),
                    models.Index(
                        fields=["is_active"], name="department_is_acti_8ce068_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Position name (e.g., Teacher I, Master Teacher I)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Brief description of this position",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date when this position was added"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date when this position was last updated",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this position is currently active",
                    ),
                ),
            ],
            options={
                "verbose_name": "Position",
                "verbose_name_plural": "Positions",
                "db_table": "position",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="position_name_f16e38_idx"),
                    models.Index(
                        fields=["is_active"], name="position_is_acti_6d370a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Program code (e.g., STE, STEM, SPFL)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Full program name", max_length=100),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Brief description of this program",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this program is currently active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date when this program was added"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date when this program was last updated",
                    ),
                ),
            ],
            options={
                "verbose_name": "Program",
                "verbose_name_plural": "Programs",
                "db_table": "program",
                "ordering": ["code"],
                "indexes": [
                    models.Index(fields=["code"], name="program_code_a92649_idx"),
                    models.Index(
                        fields=["is_active"], name="program_is_acti_0163e5_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[("admin", "Admin"), ("coordinator", "Coordinator")],
                        max_length=20,
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        help_text="Employee ID number", max_length=50, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the profile was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the profile was last updated"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="User's department",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="userprofile_set",
                        to="admin_app.department",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        help_text="User's position/rank",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="userprofile_set",
                        to="admin_app.position",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        help_text="User's program",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="userprofile_set",
                        to="admin_app.program",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_profile",
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("user_added", "User Added"),
                            ("user_updated", "User Updated"),
                            ("user_deleted", "User Deleted"),
                            ("permission_changed", "Permission Changed"),
                            ("position_added", "Position Added"),
                            ("position_updated", "Position Updated"),
                            ("position_deleted", "Position Deleted"),
                            ("department_added", "Department Added"),
                            ("department_updated", "Department Updated"),
                            ("department_deleted", "Department Deleted"),
                            ("program_added", "Program Added"),
                            ("program_updated", "Program Updated"),
                            ("program_deleted", "Program Deleted"),
                            ("content_updated", "Content Updated"),
                            ("settings_changed", "Settings Changed"),
                        ],
                        help_text="Type of action performed",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the action"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the user", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="Browser user agent", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the action was performed"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Log",
                "verbose_name_plural": "Activity Logs",
                "db_table": "activity_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="activity_lo_created_3aa675_idx"
                    ),
                    models.Index(
                        fields=["action"], name="activity_lo_action_f14761_idx"
                    ),
                    models.Index(
                        fields=["user"], name="activity_lo_user_id_ef3d5a_idx"
                    ),
                ],
            },
        ),
    ]
