# Generated by Django 6.0 on 2025-12-27 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[("admin", "Admin"), ("coordinator", "Coordinator")],
                        max_length=20,
                    ),
                ),
                (
                    "program",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("STE", "STE"),
                            ("STEM", "STEM"),
                            ("SPFL", "SPFL"),
                            ("SPTVE", "SPTVE"),
                            ("TOP5", "TOP 5"),
                            ("HETERO", "HETERO"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_profile",
            },
        ),
    ]
