# Generated by Django 6.0 on 2025-12-29 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("header", "Header Content"),
                            ("announcement", "Announcement"),
                            ("service", "Service"),
                            ("contact", "Contact Information"),
                            ("staff", "Staff/Member"),
                            ("footer", "Footer Content"),
                        ],
                        help_text="Type of content",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Title or heading of the content",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Main description or body text", null=True
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Image file for logos, announcements, or staff photos",
                        null=True,
                        upload_to="content_images/",
                    ),
                ),
                (
                    "logo_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("school", "School Logo"),
                            ("region", "Region IX Logo"),
                            ("peninsula", "Zamboanga Peninsula Logo"),
                            ("matatag", "Matatag Logo"),
                        ],
                        help_text="Type of logo (for header content)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "staff_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of staff member",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "staff_position",
                    models.CharField(
                        blank=True,
                        help_text="Position/title of staff member",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, help_text="Physical address", null=True
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Phone number", max_length=50, null=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Email address", max_length=254, null=True
                    ),
                ),
                (
                    "facebook_url",
                    models.URLField(
                        blank=True,
                        help_text="Facebook page URL",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "twitter_url",
                    models.URLField(
                        blank=True, help_text="Twitter/X URL", max_length=500, null=True
                    ),
                ),
                (
                    "instagram_url",
                    models.URLField(
                        blank=True, help_text="Instagram URL", max_length=500, null=True
                    ),
                ),
                (
                    "operating_hours",
                    models.TextField(
                        blank=True, help_text="Operating hours information", null=True
                    ),
                ),
                (
                    "copyright_text",
                    models.CharField(
                        blank=True,
                        help_text="Copyright text for footer",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "link_text",
                    models.CharField(
                        blank=True,
                        help_text="Text for additional links (footer)",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "link_url",
                    models.URLField(
                        blank=True,
                        help_text="URL for additional links",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this content is currently active/published",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order (lower numbers appear first)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this content was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this content was last updated"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this content",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_content",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        help_text="User who last updated this content",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_content",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Management",
                "verbose_name_plural": "Content Management",
                "db_table": "content_management",
                "ordering": ["content_type", "order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "is_active"],
                        name="content_man_content_a1d709_idx",
                    ),
                    models.Index(fields=["order"], name="content_man_order_d04625_idx"),
                    models.Index(
                        fields=["-created_at"], name="content_man_created_dfd79a_idx"
                    ),
                ],
            },
        ),
    ]
