# Generated by Django 6.0 on 2025-12-31 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0003_system_settings_header_logo"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="contentmanagement",
            name="content_man_content_a1d709_idx",
        ),
        migrations.RemoveIndex(
            model_name="contentmanagement",
            name="content_man_order_d04625_idx",
        ),
        migrations.RemoveIndex(
            model_name="contentmanagement",
            name="content_man_created_dfd79a_idx",
        ),
        migrations.RenameIndex(
            model_name="systemsettings",
            new_name="system_sett_setting_e69b9c_idx",
            old_name="system_settings_setting_type_idx",
        ),
        migrations.RenameIndex(
            model_name="systemsettings",
            new_name="system_sett_key_052b30_idx",
            old_name="system_settings_key_idx",
        ),
        migrations.RenameIndex(
            model_name="systemsettings",
            new_name="system_sett_is_acti_7e04e2_idx",
            old_name="system_settings_is_active_idx",
        ),
        migrations.DeleteModel(
            name="ContentManagement",
        ),
    ]
