# Generated by Django 6.0 on 2025-12-31 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "admin_app",
            "0004_remove_contentmanagement_content_man_content_a1d709_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Staff member name", max_length=200),
                ),
                (
                    "position",
                    models.CharField(
                        help_text="Staff member position/title", max_length=200
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Staff member photo",
                        null=True,
                        upload_to="staff_members/",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="Order in which to display (lower numbers first)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this staff member is currently displayed",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Member",
                "verbose_name_plural": "Staff Members",
                "db_table": "staff_member",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.RemoveField(
            model_name="headerlogo",
            name="uploaded_by",
        ),
        migrations.AlterModelOptions(
            name="systemsettings",
            options={
                "ordering": ["setting_type"],
                "verbose_name": "System Setting",
                "verbose_name_plural": "System Settings",
            },
        ),
        migrations.RemoveConstraint(
            model_name="systemsettings",
            name="unique_setting_type_key",
        ),
        migrations.RemoveIndex(
            model_name="systemsettings",
            name="system_sett_key_052b30_idx",
        ),
        migrations.RemoveIndex(
            model_name="systemsettings",
            name="system_sett_is_acti_7e04e2_idx",
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Image file for logo/image settings",
                null=True,
                upload_to="system_settings/",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="setting_value",
            field=models.TextField(
                blank=True, help_text="Setting value (text, HTML, or JSON)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="setting_type",
            field=models.CharField(
                choices=[
                    ("header_logo_school", "Header - School Logo"),
                    ("header_logo_region", "Header - Region IX Logo"),
                    ("header_logo_peninsula", "Header - Zamboanga Peninsula Logo"),
                    ("header_logo_matatag", "Header - Matatag Logo"),
                    ("header_caption", "Header - Caption"),
                    ("announcement_image", "Announcement - Image"),
                    ("announcement_caption", "Announcement - Caption"),
                    ("contact_address", "Contact - Address"),
                    ("contact_phone", "Contact - Phone"),
                    ("contact_email", "Contact - Email"),
                    ("contact_facebook", "Contact - Facebook"),
                    ("contact_hours", "Contact - Operating Hours"),
                    ("footer_copyright", "Footer - Copyright"),
                    ("footer_links", "Footer - Links (JSON)"),
                    ("footer_social", "Footer - Social Media (JSON)"),
                ],
                help_text="Type of setting",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last updated this setting",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="staffmember",
            index=models.Index(
                fields=["display_order"], name="staff_membe_display_9bf821_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffmember",
            index=models.Index(
                fields=["is_active"], name="staff_membe_is_acti_ffa4ea_idx"
            ),
        ),
        migrations.DeleteModel(
            name="HeaderLogo",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="description",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="key",
        ),
        migrations.RemoveField(
            model_name="systemsettings",
            name="value",
        ),
    ]
