# Generated by Django 6.0 on 2026-01-01 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0005_staffmember_remove_headerlogo_uploaded_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_name", models.CharField(max_length=100)),
                ("address", models.TextField(blank=True, null=True)),
                ("email", models.EmailField(max_length=255, unique=True)),
                (
                    "is_adviser",
                    models.BooleanField(
                        default=False,
                        help_text="Set to true when assigned as a section adviser (one section max).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Teacher's department",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teachers",
                        to="admin_app.department",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        help_text="Teacher's position/rank",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teachers",
                        to="admin_app.position",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher",
                "verbose_name_plural": "Teachers",
                "db_table": "teacher",
                "ordering": ["last_name", "first_name"],
                "indexes": [
                    models.Index(
                        fields=["last_name", "first_name"],
                        name="teacher_last_na_89d937_idx",
                    ),
                    models.Index(fields=["email"], name="teacher_email_9e653f_idx"),
                    models.Index(
                        fields=["is_adviser"], name="teacher_is_advi_1d6046_idx"
                    ),
                ],
            },
        ),
    ]
