# Generated by Django 6.0 on 2026-01-01 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0006_teacher"),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_number", models.CharField(max_length=10)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="admin_app.building",
                    ),
                ),
            ],
            options={
                "unique_together": {("building", "room_number")},
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("building", models.CharField(blank=True, max_length=50, null=True)),
                ("room", models.CharField(blank=True, max_length=50, null=True)),
                ("max_students", models.PositiveIntegerField(default=40)),
                ("current_students", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "adviser",
                    models.OneToOneField(
                        blank=True,
                        help_text="Teacher assigned as adviser (one section max).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="advisory_section",
                        to="admin_app.teacher",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="admin_app.program",
                    ),
                ),
            ],
            options={
                "db_table": "section",
                "ordering": ["program__code", "name"],
                "indexes": [
                    models.Index(
                        fields=["program", "name"], name="section_program_d4d240_idx"
                    ),
                    models.Index(fields=["adviser"], name="section_adviser_a601ac_idx"),
                ],
                "unique_together": {("program", "name")},
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("code", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="admin_app.program",
                    ),
                ),
            ],
            options={
                "db_table": "subject",
                "ordering": ["program__code", "name"],
                "indexes": [
                    models.Index(
                        fields=["program", "code"], name="subject_program_673f43_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="subject_is_acti_582755_idx"
                    ),
                ],
                "unique_together": {("program", "code")},
            },
        ),
    ]
