# Generated by Django 6.0 on 2026-01-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0007_building_room_section_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="room_number",
            field=models.CharField(max_length=50),
        ),
    ]
