# Generated by Django 6.0 on 2026-01-01 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0008_increase_room_number_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year_label",
                    models.CharField(
                        help_text="School year label (e.g., 2024-2025, 2023-2024)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("start_date", models.DateField(help_text="School year start date")),
                ("end_date", models.DateField(help_text="School year end date")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Mark the current active school year"
                    ),
                ),
                (
                    "enrollment_open",
                    models.BooleanField(
                        default=True,
                        help_text="Whether enrollment is open for this school year",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date when this school year was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date when this school year was last updated",
                    ),
                ),
            ],
            options={
                "db_table": "school_year",
                "ordering": ["-year_label"],
            },
        ),
        migrations.AlterModelOptions(
            name="section",
            options={"ordering": ["school_year", "program__code", "name"]},
        ),
        migrations.RemoveIndex(
            model_name="section",
            name="section_program_d4d240_idx",
        ),
        migrations.AddIndex(
            model_name="schoolyear",
            index=models.Index(
                fields=["year_label"], name="school_year_year_la_88bde5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schoolyear",
            index=models.Index(
                fields=["is_active"], name="school_year_is_acti_836d47_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schoolyear",
            index=models.Index(
                fields=["enrollment_open"], name="school_year_enrollm_a7f7ad_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="section",
            name="school_year",
            field=models.ForeignKey(
                blank=True,
                help_text="School year this section belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="admin_app.schoolyear",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("school_year", "program", "name")},
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["school_year", "program", "name"],
                name="section_school__01a8f4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["school_year"], name="section_school__54aaaf_idx"
            ),
        ),
    ]
