# Generated by Django 6.0 on 2026-01-12 01:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0010_userprofile_photo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Document name (e.g., Birth Certificate, Good Moral)",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the document requirement",
                        null=True,
                    ),
                ),
                (
                    "requirement_type",
                    models.CharField(
                        choices=[
                            ("mandatory", "Mandatory"),
                            ("optional", "Optional"),
                            ("conditional", "Conditional"),
                        ],
                        default="mandatory",
                        help_text="Whether this document is mandatory or optional",
                        max_length=20,
                    ),
                ),
                (
                    "file_format",
                    models.CharField(
                        default="pdf,jpg,jpeg,png",
                        help_text="Allowed file formats (comma-separated, e.g., pdf,jpg,png)",
                        max_length=100,
                    ),
                ),
                (
                    "max_file_size_mb",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        help_text="Maximum file size in MB",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(50.0),
                        ],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this requirement is currently active",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Display order (lower numbers appear first)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date when this requirement was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date when this requirement was last updated",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this requirement",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_document_requirements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school_year",
                    models.ForeignKey(
                        help_text="School year this requirement applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_requirements",
                        to="admin_app.schoolyear",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Requirement",
                "verbose_name_plural": "Document Requirements",
                "db_table": "document_requirement",
                "ordering": ["school_year", "order", "name"],
                "indexes": [
                    models.Index(
                        fields=["school_year", "is_active"],
                        name="document_re_school__a14a32_idx",
                    ),
                    models.Index(
                        fields=["requirement_type"],
                        name="document_re_require_504189_idx",
                    ),
                    models.Index(fields=["order"], name="document_re_order_0a4abb_idx"),
                ],
                "unique_together": {("school_year", "name")},
            },
        ),
    ]
