# Generated by Django 6.0 on 2026-01-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0011_documentrequirement"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="regular_track",
            field=models.CharField(
                blank=True,
                help_text="For Regular program sections, specify track: TOP5 or HETERO",
                max_length=20,
                null=True,
            ),
        ),
    ]
