# Generated by Django 6.0 on 2026-02-05 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0012_section_regular_track"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="section",
            options={"ordering": ["school_year", "program__code", "created_at"]},
        ),
    ]
