# Generated by Django 6.0 on 2026-02-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0013_alter_section_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="masterlist_published",
            field=models.BooleanField(
                default=False,
                help_text="Whether this section's masterlist is publicly visible on the landing page",
            ),
        ),
    ]
