# Generated by Django 6.0 on 2026-02-27 22:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0014_section_masterlist_published"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GradeLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short code (e.g. G7, G8, G9, G10)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name (e.g. Grade 7, Grade 8)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Grade Level",
                "verbose_name_plural": "Grade Levels",
                "db_table": "grade_level",
                "ordering": ["code"],
            },
        ),
        migrations.AlterModelOptions(
            name="section",
            options={
                "ordering": [
                    "school_year",
                    "program__code",
                    "grade_level__code",
                    "created_at",
                ]
            },
        ),
        migrations.AddField(
            model_name="documentrequirement",
            name="applies_to",
            field=models.CharField(
                choices=[
                    ("all", "All Enrollee Types"),
                    ("new", "New Students Only"),
                    ("transferee", "Transferees Only"),
                    ("continuing", "Continuing Students Only"),
                    ("returnee", "Returnees Only"),
                ],
                default="all",
                help_text="Which enrollee type must submit this document. 'All' covers new students and transferees. Continuing students never go through the document upload step — their docs carry over automatically.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("user_added", "User Added"),
                    ("user_updated", "User Updated"),
                    ("user_deleted", "User Deleted"),
                    ("permission_changed", "Permission Changed"),
                    ("position_added", "Position Added"),
                    ("position_updated", "Position Updated"),
                    ("position_deleted", "Position Deleted"),
                    ("department_added", "Department Added"),
                    ("department_updated", "Department Updated"),
                    ("department_deleted", "Department Deleted"),
                    ("program_added", "Program Added"),
                    ("program_updated", "Program Updated"),
                    ("program_deleted", "Program Deleted"),
                    ("content_updated", "Content Updated"),
                    ("settings_changed", "Settings Changed"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activity_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="user_agent",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="documentrequirement",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="documentrequirement",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_document_requirements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="documentrequirement",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="documentrequirement",
            name="file_format",
            field=models.CharField(
                default="pdf,jpg,jpeg,png",
                help_text="Allowed file formats (comma-separated)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="documentrequirement",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="documentrequirement",
            name="max_file_size_mb",
            field=models.DecimalField(
                decimal_places=2,
                default=5.0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0.1),
                    django.core.validators.MaxValueValidator(50.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="documentrequirement",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="documentrequirement",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="documentrequirement",
            name="requirement_type",
            field=models.CharField(
                choices=[
                    ("mandatory", "Mandatory"),
                    ("optional", "Optional"),
                    ("conditional", "Conditional"),
                ],
                default="mandatory",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="documentrequirement",
            name="school_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_requirements",
                to="admin_app.schoolyear",
            ),
        ),
        migrations.AlterField(
            model_name="documentrequirement",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="position",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="position",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="position",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="position",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="program",
            name="code",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="program",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="program",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="program",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="program",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="program",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="schoolyear",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="schoolyear",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="schoolyear",
            name="enrollment_open",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="schoolyear",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="schoolyear",
            name="start_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="schoolyear",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="schoolyear",
            name="year_label",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="section",
            name="adviser",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="advisory_section",
                to="admin_app.teacher",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="masterlist_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="section",
            name="regular_track",
            field=models.CharField(
                blank=True,
                help_text="For Regular program sections: TOP5 or HETERO",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="school_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="admin_app.schoolyear",
            ),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="display_order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="staff_members/"),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="position",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="system_settings/"
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="setting_type",
            field=models.CharField(
                choices=[
                    ("header_logo_school", "Header - School Logo"),
                    ("header_logo_region", "Header - Region IX Logo"),
                    ("header_logo_peninsula", "Header - Zamboanga Peninsula Logo"),
                    ("header_logo_matatag", "Header - Matatag Logo"),
                    ("header_caption", "Header - Caption"),
                    ("announcement_image", "Announcement - Image"),
                    ("announcement_caption", "Announcement - Caption"),
                    ("contact_address", "Contact - Address"),
                    ("contact_phone", "Contact - Phone"),
                    ("contact_email", "Contact - Email"),
                    ("contact_facebook", "Contact - Facebook"),
                    ("contact_hours", "Contact - Operating Hours"),
                    ("footer_copyright", "Footer - Copyright"),
                    ("footer_links", "Footer - Links (JSON)"),
                    ("footer_social", "Footer - Social Media (JSON)"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="setting_value",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teachers",
                to="admin_app.department",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="is_adviser",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teachers",
                to="admin_app.position",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="userprofile_set",
                to="admin_app.department",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="employee_id",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="user_profiles/"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="userprofile_set",
                to="admin_app.position",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="userprofile_set",
                to="admin_app.program",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="documentrequirement",
            index=models.Index(
                fields=["applies_to"], name="document_re_applies_4a461f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gradelevel",
            index=models.Index(fields=["code"], name="grade_level_code_30590f_idx"),
        ),
        migrations.AddIndex(
            model_name="gradelevel",
            index=models.Index(
                fields=["is_active"], name="grade_level_is_acti_16442c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="section",
            name="grade_level",
            field=models.ForeignKey(
                blank=True,
                help_text="Grade level this section handles (e.g. Grade 7, Grade 8)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sections",
                to="admin_app.gradelevel",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("school_year", "program", "grade_level", "name")},
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(
                fields=["grade_level"], name="section_grade_l_cf3696_idx"
            ),
        ),
    ]
