# Generated by Django 6.0 on 2026-03-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0015_gradelevel_alter_section_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LISStudent",
            fields=[
                (
                    "lrn",
                    models.CharField(max_length=12, primary_key=True, serialize=False),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("birth_date", models.DateField()),
                ("last_school", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "lis_students",
                "managed": True,
            },
        ),
    ]
