# Generated by Django 6.0 on 2026-03-14 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0018_documentrequirement_grade_level"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="documentrequirement",
            new_name="document_re_grade_l_f13525_idx",
            old_name="doc_req_grade_level_idx",
        ),
        migrations.AlterField(
            model_name="documentrequirement",
            name="grade_level",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, only students enrolling into this grade level see this requirement. Leave blank (NULL) for requirements that apply to all grade levels. Example: 'SF9 Gr 6 card' → set to Grade 7 (incoming Grade 7 students submit their Gr 6 card).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="document_requirements",
                to="admin_app.gradelevel",
            ),
        ),
    ]
