# Generated by Django 6.0 on 2026-03-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0021_alter_systemsettings_setting_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemsettings",
            name="setting_type",
            field=models.CharField(
                choices=[
                    ("header_logo_school", "Header - School Logo"),
                    ("carousel_slide_1_image", "Carousel - Slide 1 Image"),
                    ("carousel_slide_1_title", "Carousel - Slide 1 Title"),
                    ("carousel_slide_1_caption", "Carousel - Slide 1 Caption"),
                    ("carousel_slide_2_image", "Carousel - Slide 2 Image"),
                    ("carousel_slide_2_title", "Carousel - Slide 2 Title"),
                    ("carousel_slide_2_caption", "Carousel - Slide 2 Caption"),
                    ("carousel_slide_3_image", "Carousel - Slide 3 Image"),
                    ("carousel_slide_3_title", "Carousel - Slide 3 Title"),
                    ("carousel_slide_3_caption", "Carousel - Slide 3 Caption"),
                    ("partner_logo_1", "Partner - Logo 1"),
                    ("partner_logo_1_name", "Partner - Logo 1 Name"),
                    ("partner_logo_2", "Partner - Logo 2"),
                    ("partner_logo_2_name", "Partner - Logo 2 Name"),
                    ("partner_logo_3", "Partner - Logo 3"),
                    ("partner_logo_3_name", "Partner - Logo 3 Name"),
                    ("header_logo_region", "Header - Region IX Logo"),
                    ("header_logo_peninsula", "Header - Zamboanga Peninsula Logo"),
                    ("header_logo_matatag", "Header - Matatag Logo"),
                    ("header_caption", "Header - Caption"),
                    ("announcement_image", "Announcement - Image"),
                    ("announcement_caption", "Announcement - Caption"),
                    ("contact_address", "Contact - Address"),
                    ("contact_phone", "Contact - Phone"),
                    ("contact_email", "Contact - Email"),
                    ("contact_facebook", "Contact - Facebook"),
                    ("contact_hours", "Contact - Operating Hours"),
                    ("footer_copyright", "Footer - Copyright"),
                    ("footer_links", "Footer - Links (JSON)"),
                    ("footer_social", "Footer - Social Media (JSON)"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
