# Generated by Django 6.0 on 2026-03-22 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0022_alter_systemsettings_setting_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="adviser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="advisory_sections",
                to="admin_app.teacher",
            ),
        ),
    ]
