# Generated by Django 6.0 on 2026-03-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0023_alter_section_adviser"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="is_threshold_subject",
            field=models.BooleanField(
                default=False,
                help_text="STE only — if True, student must score >= 83 in this subject to avoid probation. Applies to Math, Science, English, Research and any future STE specialized subjects.",
            ),
        ),
    ]
