# Generated by Django 6.0 on 2026-02-22 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lis", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lisstudent",
            options={"managed": True},
        ),
    ]
