# Generated by Django 6.0 on 2025-12-29 02:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "lrn",
                    models.CharField(
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        verbose_name="LRN Number",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                (
                    "enrollment_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False, help_text="Prevents multiple submissions"
                    ),
                ),
                ("student_data_completed", models.BooleanField(default=False)),
                (
                    "student_data_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("family_data_completed", models.BooleanField(default=False)),
                (
                    "family_data_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("survey_completed", models.BooleanField(default=False)),
                ("survey_completed_at", models.DateTimeField(blank=True, null=True)),
                ("academic_data_completed", models.BooleanField(default=False)),
                (
                    "academic_data_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("program_selected", models.BooleanField(default=False)),
                ("program_selected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_lis_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the student's LRN was verified against LIS",
                    ),
                ),
                (
                    "lis_verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the LRN was verified",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "students",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EnrollmentStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=20,
                    ),
                ),
                ("changed_by", models.CharField(blank=True, max_length=255, null=True)),
                ("change_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "enrollment_status_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Guardian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("family_name", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_of_birth", models.DateField()),
                ("occupation", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True, null=True)),
                ("contact_number", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "guardian_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("father", "Father"),
                            ("mother", "Mother"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "relationship_to_student",
                    models.CharField(
                        blank=True,
                        help_text="Only for 'other' guardian type",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="guardian_photos/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "guardians",
            },
        ),
        migrations.CreateModel(
            name="AcademicData",
            fields=[
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="academic_data",
                        serialize=False,
                        to="enrollment_app.student",
                    ),
                ),
                (
                    "dost_exam_result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("not_taken", "Not Taken"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "mathematics",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "araling_panlipunan",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "english",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "edukasyon_sa_pagpapakatao",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "science",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "edukasyon_pangkabuhayan",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "filipino",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "mapeh",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "report_card",
                    models.FileField(blank=True, null=True, upload_to="report_cards/"),
                ),
                ("is_working_student", models.BooleanField(default=False)),
                ("working_type", models.TextField(blank=True, null=True)),
                ("is_pwd", models.BooleanField(default=False)),
                ("disability_type", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "academic_data",
            },
        ),
        migrations.CreateModel(
            name="FamilyData",
            fields=[
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="family_data",
                        serialize=False,
                        to="enrollment_app.student",
                    ),
                ),
                (
                    "official_guardian_type",
                    models.CharField(
                        choices=[
                            ("father", "Father"),
                            ("mother", "Mother"),
                            ("other", "Other Guardian"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "family_data",
            },
        ),
        migrations.CreateModel(
            name="ProgramSelection",
            fields=[
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="program_selection",
                        serialize=False,
                        to="enrollment_app.student",
                    ),
                ),
                (
                    "selected_program_code",
                    models.CharField(
                        help_text="Program code selected by student (e.g., STE, SPFL, TOP5)",
                        max_length=20,
                    ),
                ),
                (
                    "program_description",
                    models.TextField(help_text="Description shown during selection"),
                ),
                (
                    "selection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Why student chose this program",
                        null=True,
                    ),
                ),
                ("admin_approved", models.BooleanField(default=False)),
                ("admin_notes", models.TextField(blank=True, null=True)),
                (
                    "approved_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_section",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("section_assigned_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "program_selection",
            },
        ),
        migrations.CreateModel(
            name="StudentData",
            fields=[
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="student_data",
                        serialize=False,
                        to="enrollment_app.student",
                    ),
                ),
                ("last_name", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "place_of_birth",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("religion", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "dialect_spoken",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "ethnic_tribe",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "enrolling_as",
                    models.JSONField(
                        default=list,
                        help_text='Array of enrollment types: ["new", "transferee", "old"]',
                    ),
                ),
                ("is_sped", models.BooleanField(default=False)),
                ("sped_details", models.TextField(blank=True, null=True)),
                ("is_working_student", models.BooleanField(default=False)),
                ("working_details", models.TextField(blank=True, null=True)),
                (
                    "last_school_attended",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "previous_grade_section",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "last_school_year",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "student_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="student_photos/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "student_data",
            },
        ),
        migrations.CreateModel(
            name="SurveyData",
            fields=[
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="survey_data",
                        serialize=False,
                        to="enrollment_app.student",
                    ),
                ),
                (
                    "student_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("age", models.IntegerField(blank=True, null=True)),
                (
                    "current_grade_section",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "residence_barangay",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("gender", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "learning_style",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("study_hours", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "study_environment",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "schoolwork_support",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "enjoyed_subjects",
                    models.JSONField(
                        default=list,
                        help_text='Array of subjects: ["Math", "Science", ...]',
                    ),
                ),
                (
                    "interested_program",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "program_motivation",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "enjoyed_activities",
                    models.JSONField(default=list, help_text="Array of activities"),
                ),
                ("enjoyed_activities_other", models.TextField(blank=True, null=True)),
                (
                    "assignments_on_time",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "handle_difficult_lessons",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "device_availability",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "internet_access",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("absences", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "absence_reason",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "participation",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "difficulty_areas",
                    models.JSONField(
                        default=list, help_text="Array of difficulty areas"
                    ),
                ),
                (
                    "extra_support",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("quiet_place", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "distance_from_school",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "travel_difficulty",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "survey_responses_json",
                    models.JSONField(
                        default=dict, help_text="Complete survey responses as backup"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "survey_data",
            },
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["enrollment_status"], name="students_enrollm_559cd0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["created_at"], name="students_created_4669b8_idx"
            ),
        ),
        migrations.AddField(
            model_name="enrollmentstatuslog",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_logs",
                to="enrollment_app.student",
            ),
        ),
        migrations.AddIndex(
            model_name="guardian",
            index=models.Index(
                fields=["family_name", "first_name", "date_of_birth"],
                name="guardians_family__9d7484_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="guardian",
            index=models.Index(
                fields=["contact_number"], name="guardians_contact_92fffb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="academicdata",
            index=models.Index(
                fields=["dost_exam_result"], name="academic_da_dost_ex_7fd547_idx"
            ),
        ),
        migrations.AddField(
            model_name="familydata",
            name="father",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students_as_father",
                to="enrollment_app.guardian",
            ),
        ),
        migrations.AddField(
            model_name="familydata",
            name="mother",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students_as_mother",
                to="enrollment_app.guardian",
            ),
        ),
        migrations.AddField(
            model_name="familydata",
            name="official_guardian",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="students_as_official_guardian",
                to="enrollment_app.guardian",
            ),
        ),
        migrations.AddIndex(
            model_name="programselection",
            index=models.Index(
                fields=["selected_program_code"], name="program_sel_selecte_d61f10_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="programselection",
            index=models.Index(
                fields=["admin_approved"], name="program_sel_admin_a_b583af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="programselection",
            index=models.Index(
                fields=["assigned_section"], name="program_sel_assigne_c4a54f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentdata",
            index=models.Index(
                fields=["last_name"], name="student_dat_last_na_38f88a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentdata",
            index=models.Index(
                fields=["date_of_birth"], name="student_dat_date_of_493cf5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="surveydata",
            index=models.Index(
                fields=["interested_program"], name="survey_data_interes_9d04ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollmentstatuslog",
            index=models.Index(
                fields=["student", "new_status"], name="enrollment__student_6d152e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollmentstatuslog",
            index=models.Index(
                fields=["created_at"], name="enrollment__created_32bdec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="familydata",
            index=models.Index(
                fields=["official_guardian"], name="family_data_officia_71f174_idx"
            ),
        ),
    ]
