# Generated by Django 6.0 on 2026-01-01 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0009_schoolyear_alter_section_options_and_more"),
        ("enrollment_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="programselection",
            name="school_year",
            field=models.ForeignKey(
                blank=True,
                help_text="School year this program selection belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="program_selections",
                to="admin_app.schoolyear",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="school_year",
            field=models.ForeignKey(
                blank=True,
                help_text="School year this student enrolled in",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="admin_app.schoolyear",
            ),
        ),
        migrations.AddIndex(
            model_name="programselection",
            index=models.Index(
                fields=["school_year"], name="program_sel_school__83c7d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["school_year"], name="students_school__ab5b00_idx"
            ),
        ),
    ]
