# Generated by Django 6.0 on 2026-01-04 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "enrollment_app",
            "0002_programselection_school_year_student_school_year_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Parent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("family_name", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "parent_type",
                    models.CharField(
                        choices=[("father", "Father"), ("mother", "Mother")],
                        help_text="Is this person a father or mother",
                        max_length=10,
                    ),
                ),
                ("date_of_birth", models.DateField()),
                ("occupation", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True, null=True)),
                ("contact_number", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "parents",
            },
        ),
        migrations.RemoveIndex(
            model_name="familydata",
            name="family_data_officia_71f174_idx",
        ),
        migrations.AlterUniqueTogether(
            name="guardian",
            unique_together={
                (
                    "family_name",
                    "first_name",
                    "date_of_birth",
                    "relationship_to_student",
                )
            },
        ),
        migrations.AddField(
            model_name="familydata",
            name="other_guardian",
            field=models.ForeignKey(
                blank=True,
                help_text="Other guardian reference (only when type is 'other')",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="students_as_guardian",
                to="enrollment_app.guardian",
            ),
        ),
        migrations.AddField(
            model_name="familydata",
            name="parent_photo",
            field=models.ImageField(
                blank=True,
                help_text="Photo of the official guardian",
                null=True,
                upload_to="parent_photos/",
            ),
        ),
        migrations.AlterField(
            model_name="familydata",
            name="official_guardian_type",
            field=models.CharField(
                choices=[
                    ("father", "Father"),
                    ("mother", "Mother"),
                    ("other", "Other Guardian"),
                ],
                help_text="Who is the student's official guardian",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="guardian",
            name="relationship_to_student",
            field=models.CharField(
                help_text="Relationship to student (e.g., Grandmother, Uncle, Aunt)",
                max_length=100,
            ),
        ),
        migrations.AddIndex(
            model_name="parent",
            index=models.Index(
                fields=["family_name", "first_name", "date_of_birth"],
                name="parents_family__a214ef_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="parent",
            index=models.Index(
                fields=["contact_number"], name="parents_contact_e057a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="parent",
            index=models.Index(
                fields=["parent_type"], name="parents_parent__7ec085_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="parent",
            unique_together={
                ("family_name", "first_name", "date_of_birth", "parent_type")
            },
        ),
        migrations.AlterField(
            model_name="familydata",
            name="father",
            field=models.ForeignKey(
                help_text="Reference to father's record in Parent table",
                limit_choices_to={"parent_type": "father"},
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="students_as_father",
                to="enrollment_app.parent",
            ),
        ),
        migrations.AlterField(
            model_name="familydata",
            name="mother",
            field=models.ForeignKey(
                help_text="Reference to mother's record in Parent table",
                limit_choices_to={"parent_type": "mother"},
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="students_as_mother",
                to="enrollment_app.parent",
            ),
        ),
        migrations.AddIndex(
            model_name="familydata",
            index=models.Index(
                fields=["official_guardian_type"], name="family_data_officia_acb7d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="familydata",
            index=models.Index(
                fields=["father"], name="family_data_father__c71bba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="familydata",
            index=models.Index(
                fields=["mother"], name="family_data_mother__65b689_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="familydata",
            index=models.Index(
                fields=["other_guardian"], name="family_data_other_g_7f9038_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="familydata",
            name="official_guardian",
        ),
        migrations.RemoveField(
            model_name="guardian",
            name="guardian_type",
        ),
    ]
