# Generated by Django 6.0 on 2026-01-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment_app", "0003_parent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Guardian's email address for contact",
                max_length=254,
                null=True,
            ),
        ),
    ]
