# Generated by Django 6.0 on 2026-01-12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0011_documentrequirement'),
        ('enrollment_app', '0004_alter_student_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDocumentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_file', models.FileField(help_text='Uploaded document file', upload_to='student_documents/%Y/%m/%d/')),
                ('file_name', models.CharField(help_text='Original file name', max_length=255)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('file_format', models.CharField(help_text='File extension (e.g., pdf, jpg, png)', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resubmit', 'Resubmit Required')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True, help_text='Notes or feedback from reviewer', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Timestamp when reviewed', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_submissions', to='admin_app.documentrequirement')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Staff member who reviewed this submission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_document_submissions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_submissions', to='enrollment_app.student')),
            ],
            options={
                'db_table': 'student_document_submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='studentdocumentsubmission',
            index=models.Index(fields=['student', 'status'], name='student_doc_student_sts_idx'),
        ),
        migrations.AddIndex(
            model_name='studentdocumentsubmission',
            index=models.Index(fields=['requirement', 'status'], name='student_doc_req_sts_idx'),
        ),
        migrations.AddIndex(
            model_name='studentdocumentsubmission',
            index=models.Index(fields=['submitted_at'], name='student_doc_submit_idx'),
        ),
        migrations.AddIndex(
            model_name='studentdocumentsubmission',
            index=models.Index(fields=['status'], name='student_doc_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentdocumentsubmission',
            unique_together={('student', 'requirement')},
        ),
    ]
