# Generated by Django 6.0 on 2026-01-12 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment_app", "0005_studentdocumentsubmission"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="studentdocumentsubmission",
            new_name="student_doc_student_437eb4_idx",
            old_name="student_doc_student_sts_idx",
        ),
        migrations.RenameIndex(
            model_name="studentdocumentsubmission",
            new_name="student_doc_require_32ce2f_idx",
            old_name="student_doc_req_sts_idx",
        ),
        migrations.RenameIndex(
            model_name="studentdocumentsubmission",
            new_name="student_doc_submitt_1ee895_idx",
            old_name="student_doc_submit_idx",
        ),
        migrations.RenameIndex(
            model_name="studentdocumentsubmission",
            new_name="student_doc_status_881ca4_idx",
            old_name="student_doc_status_idx",
        ),
    ]
