# Generated by Django 6.0 on 2026-01-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "enrollment_app",
            "0006_rename_student_doc_student_sts_idx_student_doc_student_437eb4_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="studentdata",
            name="age",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Age in years (auto-computed from date of birth)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="programselection",
            name="selected_program_code",
            field=models.CharField(
                help_text="Program code selected by student (e.g., STE, SPFL, REGULAR)",
                max_length=20,
            ),
        ),
    ]
