# Generated by Django 6.0 on 2026-01-25 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment_app", "0008_add_rejection_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familydata",
            name="father",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to father's record in Parent table (Optional - may be single mother household)",
                limit_choices_to={"parent_type": "father"},
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="students_as_father",
                to="enrollment_app.parent",
            ),
        ),
        migrations.AlterField(
            model_name="familydata",
            name="mother",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to mother's record in Parent table (Optional - may be single father household)",
                limit_choices_to={"parent_type": "mother"},
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="students_as_mother",
                to="enrollment_app.parent",
            ),
        ),
        migrations.AlterField(
            model_name="familydata",
            name="official_guardian_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("father", "Father"),
                    ("mother", "Mother"),
                    ("other", "Other Guardian"),
                ],
                help_text="Who is the student's official guardian (Father, Mother, or Other)",
                max_length=10,
                null=True,
            ),
        ),
    ]
