# Generated by Django 6.0 on 2026-01-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "enrollment_app",
            "0009_alter_familydata_father_alter_familydata_mother_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="studentdata",
            name="agreed_to_terms",
            field=models.BooleanField(
                default=False, help_text="Student agreed to terms and conditions"
            ),
        ),
    ]
