# Generated by Django 6.0 on 2026-02-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment_app", "0010_studentdata_agreed_to_terms"),
    ]

    operations = [
        migrations.AddField(
            model_name="programselection",
            name="regular_track",
            field=models.CharField(
                blank=True,
                help_text="For REGULAR program: TOP5 or HETERO track",
                max_length=10,
                null=True,
            ),
        ),
    ]
