# Generated by Django 6.0 on 2026-02-27 22:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0015_gradelevel_alter_section_options_and_more"),
        ("enrollment_app", "0011_programselection_regular_track"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="programselection",
            new_name="program_sel_assigne_ffbd3e_idx",
            old_name="program_sel_assigne_c4a54f_idx",
        ),
        migrations.AlterUniqueTogether(
            name="studentdocumentsubmission",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="academicdata",
            name="overall_average",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Auto-computed average of all submitted subjects, saved on each update.",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="academicdata",
            name="report_card_grade_level",
            field=models.ForeignKey(
                blank=True,
                help_text="Grade level of the submitted report card. Grade 7 enrollee submits Grade 6 card; Grade 8 enrollee submits Grade 7 card, etc.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_report_cards",
                to="admin_app.gradelevel",
            ),
        ),
        migrations.AddField(
            model_name="programselection",
            name="requires_program_selection",
            field=models.BooleanField(
                default=True,
                help_text="True for new students — they go through AI recommendation and pick a program themselves. False for continuing and transferee students — the coordinator assigns their section and program directly.",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="documents_completed",
            field=models.BooleanField(
                default=False,
                help_text="True when all required documents are submitted or confirmed. Auto-set to True for continuing students when documents are carried over from the previous school year.",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="documents_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="enrollee_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("new", "New (Incoming Grade 7)"),
                    ("continuing", "Continuing (Old Student — Same School)"),
                    ("transferee", "Transferee (From Another School)"),
                    ("returnee", "Returnee"),
                ],
                help_text="Drives which steps are required and whether documents carry over",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="grade_level",
            field=models.ForeignKey(
                blank=True,
                help_text="Grade level the student is enrolling INTO (e.g. Grade 7, Grade 8)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="admin_app.gradelevel",
            ),
        ),
        migrations.AddField(
            model_name="studentdocumentsubmission",
            name="carried_over_from",
            field=models.ForeignKey(
                blank=True,
                help_text="Points to the original submission this was copied from. Preserved even after the student uploads a new file.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carryover_copies",
                to="enrollment_app.studentdocumentsubmission",
            ),
        ),
        migrations.AddField(
            model_name="studentdocumentsubmission",
            name="is_carried_over",
            field=models.BooleanField(
                default=False,
                help_text="True when this submission was automatically copied from a previous school year for a continuing student. The student may update it but is not required to re-upload.",
            ),
        ),
        migrations.AddField(
            model_name="studentdocumentsubmission",
            name="school_year",
            field=models.ForeignKey(
                blank=True,
                help_text="The enrollment cycle this submission belongs to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_submissions",
                to="admin_app.schoolyear",
            ),
        ),
        migrations.AlterField(
            model_name="familydata",
            name="father",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"parent_type": "father"},
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="students_as_father",
                to="enrollment_app.parent",
            ),
        ),
        migrations.AlterField(
            model_name="familydata",
            name="mother",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"parent_type": "mother"},
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="students_as_mother",
                to="enrollment_app.parent",
            ),
        ),
        migrations.AlterField(
            model_name="familydata",
            name="official_guardian_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("father", "Father"),
                    ("mother", "Mother"),
                    ("other", "Other Guardian"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="familydata",
            name="other_guardian",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="students_as_guardian",
                to="enrollment_app.guardian",
            ),
        ),
        migrations.AlterField(
            model_name="familydata",
            name="parent_photo",
            field=models.ImageField(blank=True, null=True, upload_to="parent_photos/"),
        ),
        migrations.AlterField(
            model_name="guardian",
            name="relationship_to_student",
            field=models.CharField(
                help_text="e.g. Grandmother, Uncle, Aunt", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="parent",
            name="parent_type",
            field=models.CharField(
                choices=[("father", "Father"), ("mother", "Mother")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="programselection",
            name="assigned_section",
            field=models.ForeignKey(
                blank=True,
                help_text="Final section assigned to this student after approval",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enrolled_students",
                to="admin_app.section",
            ),
        ),
        migrations.AlterField(
            model_name="programselection",
            name="program_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="programselection",
            name="regular_track",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="programselection",
            name="school_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="program_selections",
                to="admin_app.schoolyear",
            ),
        ),
        migrations.AlterField(
            model_name="programselection",
            name="selected_program_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="programselection",
            name="selection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="is_lis_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="student",
            name="lis_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentdata",
            name="age",
            field=models.PositiveIntegerField(
                blank=True, help_text="Auto-computed from date of birth", null=True
            ),
        ),
        migrations.AlterField(
            model_name="studentdata",
            name="agreed_to_terms",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="studentdocumentsubmission",
            name="document_file",
            field=models.FileField(upload_to="student_documents/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="studentdocumentsubmission",
            name="file_format",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="studentdocumentsubmission",
            name="file_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="studentdocumentsubmission",
            name="file_size",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="studentdocumentsubmission",
            name="review_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentdocumentsubmission",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentdocumentsubmission",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_document_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="surveydata",
            name="difficulty_areas",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="surveydata",
            name="enjoyed_activities",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="surveydata",
            name="enjoyed_subjects",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="surveydata",
            name="survey_responses_json",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterUniqueTogether(
            name="studentdocumentsubmission",
            unique_together={("student", "requirement", "school_year")},
        ),
        migrations.AddIndex(
            model_name="academicdata",
            index=models.Index(
                fields=["report_card_grade_level"],
                name="academic_da_report__21134d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="programselection",
            index=models.Index(
                fields=["requires_program_selection"],
                name="program_sel_require_189225_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["grade_level"], name="students_grade_l_f7d0ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["enrollee_type"], name="students_enrolle_43b9e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentdocumentsubmission",
            index=models.Index(
                fields=["school_year"], name="student_doc_school__4a54ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentdocumentsubmission",
            index=models.Index(
                fields=["is_carried_over"], name="student_doc_is_carr_f431ee_idx"
            ),
        ),
    ]
