# Generated by Django 6.0 on 2026-03-14 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "admin_app",
            "0019_rename_doc_req_grade_level_idx_document_re_grade_l_f13525_idx_and_more",
        ),
        ("enrollment_app", "0021_student_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentacademicyearstatus",
            options={"ordering": ["-school_year__year_label"]},
        ),
        migrations.AlterModelOptions(
            name="studentenrollment",
            options={"ordering": ["-school_year__year_label", "-created_at"]},
        ),
        migrations.RemoveConstraint(
            model_name="studentacademicyearstatus",
            name="unique_academic_status_per_year",
        ),
        migrations.RemoveConstraint(
            model_name="studentenrollment",
            name="unique_student_enrollment_per_year",
        ),
        migrations.RemoveIndex(
            model_name="student",
            name="students_enrollm_559cd0_idx",
        ),
        migrations.RemoveIndex(
            model_name="student",
            name="students_school__ab5b00_idx",
        ),
        migrations.RemoveIndex(
            model_name="student",
            name="students_grade_l_f7d0ec_idx",
        ),
        migrations.RemoveIndex(
            model_name="student",
            name="students_enrolle_43b9e3_idx",
        ),
        migrations.RenameIndex(
            model_name="studentacademicyearstatus",
            new_name="student_aca_student_f0bab6_idx",
            old_name="academic_status_student_year_idx",
        ),
        migrations.RenameIndex(
            model_name="studentacademicyearstatus",
            new_name="student_aca_school__0e3850_idx",
            old_name="academic_status_year_status_idx",
        ),
        migrations.RenameIndex(
            model_name="studentacademicyearstatus",
            new_name="student_aca_final_s_b13201_idx",
            old_name="academic_status_status_idx",
        ),
        migrations.RenameIndex(
            model_name="studentacademicyearstatus",
            new_name="student_aca_recorde_b028fe_idx",
            old_name="academic_status_adviser_idx",
        ),
        migrations.RenameIndex(
            model_name="studentenrollment",
            new_name="student_enr_student_e97677_idx",
            old_name="student_enrollment_student_school_year_idx",
        ),
        migrations.RenameIndex(
            model_name="studentenrollment",
            new_name="student_enr_school__3fde1c_idx",
            old_name="student_enrollment_school_status_idx",
        ),
        migrations.RenameIndex(
            model_name="studentenrollment",
            new_name="student_enr_grade_l_6ec343_idx",
            old_name="student_enrollment_grade_idx",
        ),
        migrations.RenameIndex(
            model_name="studentenrollment",
            new_name="student_enr_enrolle_85e4fb_idx",
            old_name="student_enrollment_type_idx",
        ),
        migrations.RenameIndex(
            model_name="studentenrollment",
            new_name="student_enr_enrollm_a2fec8_idx",
            old_name="student_enrollment_status_idx",
        ),
        migrations.AlterField(
            model_name="student",
            name="academic_data_completed",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="documents_completed",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="[DEPRECATED] Use StudentEnrollment.documents_completed instead",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="enrollee_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("new", "New (Incoming Grade 7)"),
                    ("continuing", "Continuing (Old Student — Same School)"),
                    ("transferee", "Transferee (From Another School)"),
                    ("returnee", "Returnee"),
                ],
                help_text="[DEPRECATED] Use StudentEnrollment.enrollee_type instead",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="enrollment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("under_review", "Under Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                help_text="[DEPRECATED] Use StudentEnrollment.enrollment_status instead",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="family_data_completed",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="grade_level",
            field=models.ForeignKey(
                blank=True,
                help_text="[DEPRECATED] Use StudentEnrollment.grade_level instead",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students_deprecated",
                to="admin_app.gradelevel",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="is_locked",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="[DEPRECATED] Use StudentEnrollment.is_locked instead",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="program_selected",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="school_year",
            field=models.ForeignKey(
                blank=True,
                help_text="[DEPRECATED] Use StudentEnrollment.school_year instead",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students_deprecated",
                to="admin_app.schoolyear",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_data_completed",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="survey_completed",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="studentacademicyearstatus",
            unique_together={("student", "school_year")},
        ),
        migrations.AlterUniqueTogether(
            name="studentenrollment",
            unique_together={("student", "school_year")},
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["is_active"], name="students_is_acti_4aecc9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["is_lis_verified"], name="students_is_lis__0b47e0_idx"
            ),
        ),
    ]
