# Generated by Django 6.0 on 2026-03-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment_app", "0022_alter_studentacademicyearstatus_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentdata",
            name="previous_program",
            field=models.CharField(
                blank=True,
                choices=[
                    ("REGULAR", "Regular Track"),
                    ("STE", "STE (Science, Technology, Engineering)"),
                    ("SPTVE", "SPTVE (Sports, Physical, Technical, Vocational)"),
                    ("SPFL", "SPFL (Special Programs)"),
                ],
                default="REGULAR",
                help_text="Program type from previous school. Only for transferees; defaults to REGULAR.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="studentdata",
            name="transferee_grade_level",
            field=models.CharField(
                blank=True,
                help_text="Grade level for transferee enrollment (7-10). Empty for new/continuing students.",
                max_length=2,
                null=True,
            ),
        ),
    ]
