# Generated by Django 6.0 on 2026-03-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment_app", "0023_studentdata_previous_program_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentdata",
            name="coordinator_selected_track",
            field=models.CharField(
                blank=True,
                choices=[("TOP5", "Top-5 Regular"), ("HETERO", "Hetero Regular")],
                help_text="For REGULAR program transferees: coordinator-selected category for placement",
                max_length=20,
                null=True,
            ),
        ),
    ]
