# Generated by Django 6.0 on 2026-01-03 23:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Qualified_for_ste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_lrn",
                    models.CharField(
                        help_text="Learner Reference Number of the student",
                        max_length=12,
                        verbose_name="Student LRN",
                    ),
                ),
                (
                    "exam_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Exam score (0-100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "interview_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Interview score (0-100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("qualified", "Qualified"),
                            ("not_qualified", "Not Qualified"),
                            ("waitlisted", "Waitlisted"),
                        ],
                        default="pending",
                        help_text="Current qualification status",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when record was last updated",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True, help_text="Additional remarks or notes", null=True
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ste_qualifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Qualified for STE",
                "verbose_name_plural": "Qualified for STE",
                "db_table": "qualified_for_ste",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["student_lrn"], name="qualified_f_student_337bf7_idx"
                    ),
                    models.Index(
                        fields=["status"], name="qualified_f_status_291d9b_idx"
                    ),
                    models.Index(
                        fields=["-updated_at"], name="qualified_f_updated_a771d3_idx"
                    ),
                ],
            },
        ),
    ]
