# Generated by Django 6.0 on 2026-01-13 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coordinator_app", "0002_aiassistantpreference"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="aiassistantpreference",
            new_name="ai_assistan_user_id_566340_idx",
            old_name="ai_assista_user_id_program_9a3f5e_idx",
        ),
        migrations.RenameIndex(
            model_name="aiassistantpreference",
            new_name="ai_assistan_user_id_7f6f92_idx",
            old_name="ai_assista_user_id_1b2c3d_idx",
        ),
        migrations.RenameIndex(
            model_name="aiassistantpreference",
            new_name="ai_assistan_program_159b0c_idx",
            old_name="ai_assista_program_4e5f6g_idx",
        ),
    ]
