# Generated by Django 6.0 on 2026-02-06 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0013_alter_section_options"),
        (
            "coordinator_app",
            "0003_rename_ai_assista_user_id_program_9a3f5e_idx_ai_assistan_user_id_566340_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SectionMasterlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(help_text="Section name or code", max_length=100),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="PDF file of the section masterlist",
                        upload_to="section_masterlists/",
                    ),
                ),
                (
                    "upload_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when masterlist was uploaded",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        help_text="Program for which masterlist is uploaded",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_masterlists",
                        to="admin_app.program",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Coordinator who uploaded the masterlist",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_masterlists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "section_masterlist",
                "ordering": ["-upload_date"],
                "indexes": [
                    models.Index(
                        fields=["program"], name="section_mas_program_1dc792_idx"
                    ),
                    models.Index(
                        fields=["section"], name="section_mas_section_7f475d_idx"
                    ),
                    models.Index(
                        fields=["-upload_date"], name="section_mas_upload__be2213_idx"
                    ),
                ],
            },
        ),
    ]
