# Generated by Django 6.0 on 2026-02-17 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0014_section_masterlist_published"),
        ("coordinator_app", "0004_sectionmasterlist"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoordinatorActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("student_approved", "Student Approved"),
                            ("student_rejected", "Student Rejected"),
                            ("student_reverted", "Enrollment Reverted"),
                            ("batch_approved", "Batch Approval"),
                            ("batch_rejected", "Batch Rejection"),
                            ("section_assigned", "Section Assigned"),
                            ("section_transferred", "Section Transfer"),
                            ("section_created", "Section Created"),
                            ("section_updated", "Section Updated"),
                            ("masterlist_published", "Masterlist Published"),
                            ("masterlist_unpublished", "Masterlist Unpublished"),
                            ("student_edited", "Student Info Edited"),
                            ("student_viewed", "Student Profile Viewed"),
                            ("grades_uploaded", "Grades Uploaded"),
                            ("results_uploaded", "Results Uploaded"),
                            ("report_generated", "Report Generated"),
                            ("report_downloaded", "Report Downloaded"),
                            ("template_downloaded", "Template Downloaded"),
                            ("ai_recommendation_applied", "AI Recommendation Applied"),
                            (
                                "ai_recommendation_rejected",
                                "AI Recommendation Rejected",
                            ),
                            ("login", "Coordinator Login"),
                            ("logout", "Coordinator Logout"),
                            ("settings_changed", "Settings Changed"),
                            ("masterlist_uploaded", "Masterlist Uploaded"),
                        ],
                        help_text="Type of action performed",
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("enrollment", "Enrollment"),
                            ("section", "Section"),
                            ("student", "Student"),
                            ("report", "Report"),
                            ("ai", "AI"),
                            ("system", "System"),
                        ],
                        default="system",
                        help_text="Category of the action for filtering",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the action"),
                ),
                (
                    "student_lrn",
                    models.CharField(
                        blank=True,
                        help_text="LRN of the student involved (if applicable)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "student_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the student involved (if applicable)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "section_name",
                    models.CharField(
                        blank=True,
                        help_text="Section involved (if applicable)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata about the action (JSON)",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the coordinator", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the action was performed"
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        help_text="Program context for the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coordinator_activity_logs",
                        to="admin_app.program",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Coordinator who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coordinator_activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Coordinator Activity Log",
                "verbose_name_plural": "Coordinator Activity Logs",
                "db_table": "coordinator_activity_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="coordinator_created_e86953_idx"
                    ),
                    models.Index(
                        fields=["action"], name="coordinator_action_f47cd3_idx"
                    ),
                    models.Index(
                        fields=["category"], name="coordinator_categor_784e99_idx"
                    ),
                    models.Index(
                        fields=["user"], name="coordinator_user_id_876b5a_idx"
                    ),
                    models.Index(
                        fields=["program"], name="coordinator_program_0ae2fb_idx"
                    ),
                    models.Index(
                        fields=["student_lrn"], name="coordinator_student_bbe9dd_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CoordinatorGeneratedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_name",
                    models.CharField(
                        help_text="Display name of the report", max_length=255
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("enrollment", "Enrollment Report"),
                            ("academic", "Academic Performance Report"),
                            ("sections", "Section Assignment Report"),
                            ("custom", "Custom Report"),
                        ],
                        help_text="Type of report generated",
                        max_length=20,
                    ),
                ),
                (
                    "file_format",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF Document"),
                            ("Excel", "Excel Spreadsheet"),
                            ("Word", "Word Document"),
                        ],
                        help_text="File format (PDF, Excel, Word)",
                        max_length=10,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Generated report file",
                        upload_to="coordinator_reports/",
                    ),
                ),
                (
                    "file_size",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Human-readable file size",
                        max_length=20,
                    ),
                ),
                (
                    "program_code",
                    models.CharField(
                        help_text="Program code (STE, REGULAR, etc.)", max_length=20
                    ),
                ),
                (
                    "filter_used",
                    models.CharField(
                        blank=True,
                        default="All",
                        help_text="Filter applied when generating",
                        max_length=100,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the report was generated"
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Coordinator who generated the report",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coordinator_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "coor_generated_report",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["program_code"], name="coor_genera_program_ce9ddd_idx"
                    ),
                    models.Index(
                        fields=["generated_by"], name="coor_genera_generat_348482_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="coor_genera_created_9701c5_idx"
                    ),
                ],
            },
        ),
    ]
