# Generated by Django 6.0 on 2026-02-27 22:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0015_gradelevel_alter_section_options_and_more"),
        ("coordinator_app", "0005_coordinatoractivitylog_coordinatorgeneratedreport"),
        (
            "enrollment_app",
            "0012_rename_program_sel_assigne_c4a54f_idx_program_sel_assigne_ffbd3e_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quarter",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Quarter 1"),
                            (2, "Quarter 2"),
                            (3, "Quarter 3"),
                            (4, "Quarter 4"),
                        ]
                    ),
                ),
                ("grade", models.DecimalField(decimal_places=2, max_digits=5)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "academic_performance",
                "ordering": [
                    "student",
                    "grade_level",
                    "school_year",
                    "quarter",
                    "subject",
                ],
            },
        ),
        migrations.AddField(
            model_name="qualified_for_ste",
            name="grade_level",
            field=models.ForeignKey(
                blank=True,
                help_text="Grade level this qualification is for (e.g. Grade 7 or Grade 9 transferee)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ste_qualifications",
                to="admin_app.gradelevel",
            ),
        ),
        migrations.AddField(
            model_name="qualified_for_ste",
            name="school_year",
            field=models.ForeignKey(
                blank=True,
                help_text="School year this qualification belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ste_qualifications",
                to="admin_app.schoolyear",
            ),
        ),
        migrations.AlterField(
            model_name="aiassistantpreference",
            name="ai_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="aiassistantpreference",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="aiassistantpreference",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_preferences",
                to="admin_app.program",
            ),
        ),
        migrations.AlterField(
            model_name="aiassistantpreference",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="aiassistantpreference",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="coordinatoractivitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("student_approved", "Student Approved"),
                    ("student_rejected", "Student Rejected"),
                    ("student_reverted", "Enrollment Reverted"),
                    ("batch_approved", "Batch Approval"),
                    ("batch_rejected", "Batch Rejection"),
                    ("section_assigned", "Section Assigned"),
                    ("section_transferred", "Section Transfer"),
                    ("section_created", "Section Created"),
                    ("section_updated", "Section Updated"),
                    ("masterlist_published", "Masterlist Published"),
                    ("masterlist_unpublished", "Masterlist Unpublished"),
                    ("student_edited", "Student Info Edited"),
                    ("student_viewed", "Student Profile Viewed"),
                    ("grades_uploaded", "Grades Uploaded"),
                    ("results_uploaded", "Results Uploaded"),
                    ("report_generated", "Report Generated"),
                    ("report_downloaded", "Report Downloaded"),
                    ("template_downloaded", "Template Downloaded"),
                    ("ai_recommendation_applied", "AI Recommendation Applied"),
                    ("ai_recommendation_rejected", "AI Recommendation Rejected"),
                    ("login", "Coordinator Login"),
                    ("logout", "Coordinator Logout"),
                    ("settings_changed", "Settings Changed"),
                    ("masterlist_uploaded", "Masterlist Uploaded"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="coordinatoractivitylog",
            name="category",
            field=models.CharField(
                choices=[
                    ("enrollment", "Enrollment"),
                    ("section", "Section"),
                    ("student", "Student"),
                    ("report", "Report"),
                    ("ai", "AI"),
                    ("system", "System"),
                ],
                default="system",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="coordinatoractivitylog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="coordinatoractivitylog",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="coordinatoractivitylog",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coordinatoractivitylog",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="coordinatoractivitylog",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coordinator_activity_logs",
                to="admin_app.program",
            ),
        ),
        migrations.AlterField(
            model_name="coordinatoractivitylog",
            name="section_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="coordinatoractivitylog",
            name="student_lrn",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="coordinatoractivitylog",
            name="student_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="coordinatoractivitylog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coordinator_activity_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="coordinatorgeneratedreport",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="coordinatorgeneratedreport",
            name="file",
            field=models.FileField(upload_to="coordinator_reports/"),
        ),
        migrations.AlterField(
            model_name="coordinatorgeneratedreport",
            name="file_format",
            field=models.CharField(
                choices=[
                    ("PDF", "PDF Document"),
                    ("Excel", "Excel Spreadsheet"),
                    ("Word", "Word Document"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="coordinatorgeneratedreport",
            name="file_size",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="coordinatorgeneratedreport",
            name="filter_used",
            field=models.CharField(blank=True, default="All", max_length=100),
        ),
        migrations.AlterField(
            model_name="coordinatorgeneratedreport",
            name="generated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coordinator_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="coordinatorgeneratedreport",
            name="program_code",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="coordinatorgeneratedreport",
            name="report_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="coordinatorgeneratedreport",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("enrollment", "Enrollment Report"),
                    ("academic", "Academic Performance Report"),
                    ("sections", "Section Assignment Report"),
                    ("custom", "Custom Report"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="qualified_for_ste",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="qualified_for_ste",
            name="exam_score",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="qualified_for_ste",
            name="interview_score",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="qualified_for_ste",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="qualified_for_ste",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("qualified", "Qualified"),
                    ("not_qualified", "Not Qualified"),
                    ("waitlisted", "Waitlisted"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="qualified_for_ste",
            name="student_lrn",
            field=models.CharField(max_length=12, verbose_name="Student LRN"),
        ),
        migrations.AlterField(
            model_name="qualified_for_ste",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="qualified_for_ste",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ste_qualifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="sectionmasterlist",
            name="file",
            field=models.FileField(upload_to="section_masterlists/"),
        ),
        migrations.AlterField(
            model_name="sectionmasterlist",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="section_masterlists",
                to="admin_app.program",
            ),
        ),
        migrations.AlterField(
            model_name="sectionmasterlist",
            name="section",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="sectionmasterlist",
            name="upload_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="sectionmasterlist",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_masterlists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="qualified_for_ste",
            unique_together={("student_lrn", "grade_level", "school_year")},
        ),
        migrations.AddIndex(
            model_name="qualified_for_ste",
            index=models.Index(
                fields=["grade_level"], name="qualified_f_grade_l_1c8f14_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qualified_for_ste",
            index=models.Index(
                fields=["school_year"], name="qualified_f_school__320c14_idx"
            ),
        ),
        migrations.AddField(
            model_name="academicperformance",
            name="grade_level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_performances",
                to="admin_app.gradelevel",
            ),
        ),
        migrations.AddField(
            model_name="academicperformance",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_performances",
                to="admin_app.program",
            ),
        ),
        migrations.AddField(
            model_name="academicperformance",
            name="school_year",
            field=models.ForeignKey(
                blank=True,
                help_text="School year this performance record belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_performances",
                to="admin_app.schoolyear",
            ),
        ),
        migrations.AddField(
            model_name="academicperformance",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_performances",
                to="admin_app.section",
            ),
        ),
        migrations.AddField(
            model_name="academicperformance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_performances",
                to="enrollment_app.student",
            ),
        ),
        migrations.AddField(
            model_name="academicperformance",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_performances",
                to="admin_app.subject",
            ),
        ),
        migrations.AddIndex(
            model_name="academicperformance",
            index=models.Index(
                fields=["student"], name="academic_pe_student_8f1284_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="academicperformance",
            index=models.Index(
                fields=["section"], name="academic_pe_section_21ee33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="academicperformance",
            index=models.Index(
                fields=["program"], name="academic_pe_program_c6b4cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="academicperformance",
            index=models.Index(
                fields=["grade_level"], name="academic_pe_grade_l_4af755_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="academicperformance",
            index=models.Index(
                fields=["quarter"], name="academic_pe_quarter_17d3df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="academicperformance",
            index=models.Index(
                fields=["school_year"], name="academic_pe_school__bd1d32_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="academicperformance",
            unique_together={
                ("student", "school_year", "grade_level", "subject", "quarter")
            },
        ),
    ]
