# Generated by Django 6.0 on 2026-03-03 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0017_seed_grade_levels"),
        ("coordinator_app", "0007_probationrecord"),
        (
            "enrollment_app",
            "0012_rename_program_sel_assigne_c4a54f_idx_program_sel_assigne_ffbd3e_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="probationrecord",
            name="unique_probation_per_student_grade_year",
        ),
        migrations.RenameIndex(
            model_name="probationrecord",
            new_name="probation_r_student_feff67_idx",
            old_name="probation_student_idx",
        ),
        migrations.RenameIndex(
            model_name="probationrecord",
            new_name="probation_r_school__3391c0_idx",
            old_name="probation_school_year_idx",
        ),
        migrations.RenameIndex(
            model_name="probationrecord",
            new_name="probation_r_grade_l_370b94_idx",
            old_name="probation_grade_level_idx",
        ),
        migrations.RenameIndex(
            model_name="probationrecord",
            new_name="probation_r_is_acti_cdbc31_idx",
            old_name="probation_is_active_idx",
        ),
        migrations.RenameIndex(
            model_name="probationrecord",
            new_name="probation_r_flagged_bebeea_idx",
            old_name="probation_flagged_at_idx",
        ),
        migrations.AlterField(
            model_name="probationrecord",
            name="flagged_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Coordinator or admin who created this probation record.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flagged_probations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="probationrecord",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="True while probation is enforced. Set to False when the student appeals successfully or is reinstated.",
            ),
        ),
        migrations.AlterField(
            model_name="probationrecord",
            name="reason",
            field=models.TextField(
                help_text="Human-readable explanation of why probation was triggered. e.g. 'Math Q4: 80, Science Q4: 79 — both below the 83 retention threshold.'"
            ),
        ),
        migrations.AlterField(
            model_name="probationrecord",
            name="reinstated_at",
            field=models.DateTimeField(
                blank=True, help_text="When the reinstatement was approved.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="probationrecord",
            name="reinstated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Coordinator or admin who approved reinstatement.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reinstated_probations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="probationrecord",
            name="reinstatement_reason",
            field=models.TextField(
                blank=True,
                help_text="Reason given for reinstating the student to their original program.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="probationrecord",
            name="school_year",
            field=models.ForeignKey(
                help_text="School year in which the probation was assessed (the year they failed the threshold).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="probation_records",
                to="admin_app.schoolyear",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="probationrecord",
            unique_together={("student", "school_year", "grade_level")},
        ),
    ]
