# Generated by Django 6.0 on 2026-03-14 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coordinator_app", "0009_gradeuploadbatch_academicperformance_upload_batch"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="gradeuploadbatch",
            new_name="grade_uploa_section_1cc37c_idx",
            old_name="grade_batch_section_q_idx",
        ),
        migrations.RenameIndex(
            model_name="gradeuploadbatch",
            new_name="grade_uploa_uploade_dd7114_idx",
            old_name="grade_batch_uploaded_idx",
        ),
        migrations.AlterField(
            model_name="academicperformance",
            name="quarter",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1st Quarter"),
                    (2, "2nd Quarter"),
                    (3, "3rd Quarter"),
                    (4, "4th Quarter"),
                    (5, "Final Grade"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="gradeuploadbatch",
            name="quarter",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1st Quarter"),
                    (2, "2nd Quarter"),
                    (3, "3rd Quarter"),
                    (4, "4th Quarter"),
                    (5, "Final Grade"),
                ]
            ),
        ),
    ]
