"""
Django settings for section_placement_system project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-y0!cfpq3s+9yv6@@9z3wnuge+#f*ap7v_ydo^fy+u&9tm4p2#1"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "enrollment_app",
    "admin_app",
    "coordinator_app",
    
    "lis",  # Dummy LIS app for database connection
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "section_placement_system.urls"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'enrollment_app' / 'templates',
            BASE_DIR / 'admin_app' / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = "section_placement_system.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {  # Enrollment system database
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'program_recommendation_db',
        'USER': 'postgres',
        'PASSWORD': '011304',
        'HOST': 'localhost',
        'PORT': '5432',
    },

    'lis': {  # Dummy LIS database (READ-ONLY)
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'lis_db',
        'USER': 'postgres',
        'PASSWORD': '011304',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

DATABASE_ROUTERS = ['lis.db_router.LISRouter']




# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'shared_assets' / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ============================================
# Document AI OCR configuration
# ============================================

# Try to load pre-configured values from django_settings_documentai.py
try:
    from docs.django_settings_documentai import (
        GOOGLE_CLOUD_PROJECT as _GOOGLE_CLOUD_PROJECT,
        DOCUMENT_AI_PROCESSOR_ID as _DOCUMENT_AI_PROCESSOR_ID,
        DOCUMENT_AI_LOCATION as _DOCUMENT_AI_LOCATION,
        OCR_CONFIG as _OCR_CONFIG,
    )
except Exception:
    _GOOGLE_CLOUD_PROJECT = None
    _DOCUMENT_AI_PROCESSOR_ID = None
    _DOCUMENT_AI_LOCATION = None
    _OCR_CONFIG = None

# Environment overrides or defaults
GOOGLE_CLOUD_PROJECT = os.environ.get('GOOGLE_CLOUD_PROJECT') or os.environ.get('GCP_PROJECT_ID') or _GOOGLE_CLOUD_PROJECT or '1094485135926'
DOCUMENT_AI_PROCESSOR_ID = os.environ.get('DOCUMENT_AI_PROCESSOR_ID') or _DOCUMENT_AI_PROCESSOR_ID or 'a0cbcc2e3afe7ae0'
DOCUMENT_AI_LOCATION = os.environ.get('DOCUMENT_AI_LOCATION') or _DOCUMENT_AI_LOCATION or 'us'

# Consolidated OCR config consumed by OCRGradeVerifier
OCR_CONFIG = _OCR_CONFIG or {
    'tolerance': 3.0,
    'use_document_ai': True,
    'async_processing': False,
    'batch_size': 10,
    'subject_tolerance': 0.70,
    'row_y_padding': 35,
    'column_pad': 50,
}

# Ensure IDs are present
OCR_CONFIG.update({
    'project_id': GOOGLE_CLOUD_PROJECT,
    'processor_id': DOCUMENT_AI_PROCESSOR_ID,
    'location': DOCUMENT_AI_LOCATION,
})


